---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-a
  namespace: production
  labels:
    app: prod-nginx-pods
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: longhorn-vol
  volumes:
    - name: longhorn-vol
      persistentVolumeClaim:
        claimName: longhorn-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-b
  namespace: production
  labels:
    app: prod-nginx-pods
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: longhorn-vol
  volumes:
    - name: longhorn-vol
      persistentVolumeClaim:
        claimName: longhorn-pvc
