---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-a
  namespace: production
  labels:
    app: prod-nginx-pods
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-b
  namespace: production
  labels:
    app: prod-nginx-pods
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
