---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: myns
  labels:
    app: pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /pvmount/
          name: longhorn-vol
  volumes:
    - name: longhorn-vol
      persistentVolumeClaim:
        claimName: longhorn-pvc-b
