apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-a
  namespace: myns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-b
  namespace: myns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
