---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prod-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.100.120-192.168.100.130
  serviceAllocation:
    namespaces:
      - production
