---
apiVersion: v1
kind: Service
metadata:
  name: dept1-svc
  namespace: myns
spec:
  type: NodePort
  selector:
    app: nginx-pods
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
